export const SET_CURRENT_EXERCISE = 'SET_CURRENT_EXERCISE'
export const SUBMIT_WORKOUT = 'SUBMIT_WORKOUT'
export const SAVE_WORKOUT = 'SAVE_WORKOUT'
export const TOGGLE_SHOWING_WORKOUT = 'TOGGLE_SHOWING_WORKOUT'
